### ISSUE TITLE
CollisionData not found in TA

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#108]
I get this error:

```
ESC[36mcp3_ta    |ESC[0m Traceback (most recent call last):
ESC[36mcp3_ta    |ESC[0m   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
ESC[36mcp3_ta    |ESC[0m     cb(msg)
ESC[36mcp3_ta    |ESC[0m   File "/usr/src/app/cp3.py", line 292, in bumped
ESC[36mcp3_ta    |ESC[0m     self.bump_callback(True, be.velocity, rospy.Time.now())
ESC[36mcp3_ta    |ESC[0m   File "/usr/src/app/swagger_server/controllers/default_controller.py", line 263, in collision_cb
ESC[36mcp3_ta    |ESC[0m     config.collisions.append(CollisionData(robot_x=x,
ESC[36mcp3_ta    |ESC[0m NameError: name 'CollisionData' is not defined
```

**Comment by ivoysey** [comment]
@schmerl I'm guessing this is fixed since you closed it?

**Comment by schmerl** [comment]
Yes.
