### ISSUE TITLE
Error in IG server

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#87]
@bradley, this error happened after your changes for #84. 

```
cp1_ta    | Traceback (most recent call last):
cp1_ta    |   File "/home/mars/catkin_ws/src/ig-interpreter/ig_action_server/src/ig_server.py", line 37, in <module>
cp1_ta    | No module named brass_gazebo_plugins.srv
cp1_ta    |     import cp3_instructions as cp3
cp1_ta    |   File "/home/mars/catkin_ws/src/ig-interpreter/ig_action_server/src/cp3_instructions.py", line 6, in <module>
cp1_ta    |     from brass_gazebo_plugins.srv import *
cp1_ta    | ImportError: No module named brass_gazebo_plugins.srv
cp1_ta    | WARNING: yacc table file version is out of date
cp1_ta    | Generating LALR tables
```

**Comment by schmerl** [comment]
This is not an error. In cp1, cp3 doesn't exist; in cp3, cp1 doesn't exist. Yet we have an ig interpreter that needs to manage both. I've updated the tracing to say "Not an error".

**Comment by pooyanjamshidi** [comment]
`ImportError` is not an error?! PS. the problem still exists...

**Comment by schmerl** [comment]
It is not an error. Read the code.

**Comment by schmerl** [comment]
Import error is not an error. Read the code

**Comment by pooyanjamshidi** [comment]
So I should ignore it?

**Comment by schmerl** [comment]
Yes. You should ignore it. It even has a trace message that says this is
not an error.
